# Generated by Django 5.2.7 on 2025-11-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Supervisor / Technician'), ('B', 'Office Staff'), ('C', 'Manager / Coordinator / Marketing')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_no',
            field=models.CharField(default='0', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('on_duty', 'On Duty'), ('leave', 'Leave')], default='on_duty', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('job_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('leave_type', models.CharField(blank=True, choices=[('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('annual', 'Annual Leave'), ('compensatory', 'Compensatory Leave')], max_length=50, null=True)),
                ('leave_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_entries', to='timesheet.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
