# Generated by Django 5.2.7 on 2025-11-09 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_employee_category_employee_emp_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on_duty', 'On Duty'), ('leave', 'Leave')], default='on_duty', max_length=20)),
                ('task_title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('job_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_type', models.CharField(blank=True, choices=[('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('annual', 'Annual Leave'), ('compensatory', 'Compensatory Leave')], max_length=50, null=True)),
                ('leave_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='timesheet.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('annual', 'Annual Leave'), ('compensatory', 'Compensatory Leave')], max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=1, help_text='Number of leave days')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='timesheet.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkEntry',
        ),
    ]
