# Generated by Django 5.2.7 on 2025-11-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_job_leaverecord_delete_workentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('annual', 'Annual Leave'), ('compensatory', 'Compensatory Leave')], max_length=50)),
                ('total_allocated', models.PositiveIntegerField(default=0)),
                ('used', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='timesheet.employee')),
            ],
            options={
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
