# Generated by Django 5.2.7 on 2025-11-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_leavebalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['employee__user__username', 'leave_type']},
        ),
    ]
