# Generated by Django 5.2.7 on 2025-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_alter_leavebalance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='driv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='holiday_worked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='local_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='off_station',
            field=models.BooleanField(default=False),
        ),
    ]
