# Generated by Django 5.2.7 on 2025-11-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_job_driv_job_holiday_worked_job_local_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='worked_on',
            field=models.BooleanField(default=False),
        ),
    ]
