# Generated by Django 5.2.7 on 2025-11-11 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_job_worked_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
