# Generated by Django 5.2.7 on 2025-11-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_alter_leaverecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='worked_on',
        ),
    ]
