# Generated by Django 5.2.7 on 2025-11-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_remove_job_worked_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
    ]
