# Generated by Django 5.2.7 on 2025-11-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='task_title',
        ),
    ]
