# Generated by Django 5.2.7 on 2025-12-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0011_remove_job_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecord',
            name='count',
        ),
        migrations.RemoveField(
            model_name='leaverecord',
            name='date',
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick', 'Sick'), ('casual', 'Casual'), ('annual', 'Annual Leave'), ('compoff', 'Comp-Off'), ('lossofpay', 'Loss of Pay'), ('restrictedholiday', 'Restricted Holiday')], max_length=50, null=True),
        ),
    ]
