# Generated by Django 5.2.7 on 2025-12-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_remove_leaverecord_count_remove_leaverecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick'), ('casual', 'Casual'), ('annual', 'Annual Leave'), ('compoff', 'Comp-Off'), ('lossofpay', 'Loss of Pay'), ('restrictedholiday', 'Restricted Holiday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick'), ('casual', 'Casual'), ('annual', 'Annual Leave'), ('compoff', 'Comp-Off'), ('lossofpay', 'Loss of Pay'), ('restrictedholiday', 'Restricted Holiday')], max_length=50),
        ),
    ]
