# Generated by Django 5.2.7 on 2025-12-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0014_job_approved_at_job_approved_by_job_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick', 'Sick'), ('casual', 'Casual'), ('annual', 'Annual Leave')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick'), ('casual', 'Casual'), ('annual', 'Annual Leave')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick'), ('casual', 'Casual'), ('annual', 'Annual Leave')], max_length=50),
        ),
    ]
